site_name: Antlia - Flat design GUI for Python
theme: material
markdown_extensions:
  - codehilite
pages:
  - Home: 'index.md'
  - Examples:
    - Hello World: 'examples/helloworld.md'
    - Calculator: 'examples/calculator.md'
    - Form: 'examples/form.md'
    - Music Player: 'examples/musicplayer.md'
    - Gallery: 'examples/gallery.md'
  - Elements:
    - Grid: 'elements/grid.md'
    - Form: 'elements/form.md'
    - Other: 'elements/other.md'
  - Layout:
    - Colors: 'layout/colors.md'
    - Icons: 'layout/icons.md'
